/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_learnffmpeg_config_ConfigInfo */

#ifndef _Included_com_example_learnffmpeg_config_ConfigInfo
#define _Included_com_example_learnffmpeg_config_ConfigInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_learnffmpeg_config_ConfigInfo
 * Method:    getConfigInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_learnffmpeg_config_ConfigInfo_getConfigInfo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
